# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Groeifabriek
    Domain: groeifabriek.nl
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
        SANS: 
          - hlf-orderer--groeifabriek--orderer0
      - Hostname: orderer1
        SANS: 
          - hlf-orderer--groeifabriek--orderer1
  - Name: Pivt
    Domain: pivt.nl
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
        SANS: 
          - hlf-orderer--pivt--orderer0
      
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Karga
    Domain: aptalkarga.tr
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS: 
        - "hlf-peer--karga--{{.Hostname}}"
    Users:
      Count: 1
  
  - Name: Nevergreen
    Domain: nevergreen.nl
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS: 
        - "hlf-peer--nevergreen--{{.Hostname}}"
    Users:
      Count: 1

  - Name: Atlantis
    Domain: atlantis.com
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS: 
        - "hlf-peer--atlantis--{{.Hostname}}"
    Users:
      Count: 1