# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Groeifabriek
    Domain: groeifabriek.nl
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Karga
    Domain: aptalkarga.tr
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  
  - Name: Cimmeria
    Domain: cimmeria.hage
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
      
# ---------------------------------------------------------------------------
# Used to create external peer org MSP secrets. 
# Required to create channels where external peer orgs participate.
# Additionally init.sh script creates empty placeholder MSP folders for convenience.
# It's user's responsibility to copy MSP certificates to created folders.
# ---------------------------------------------------------------------------
ExternalPeerOrgs:
  - Name: Atlantis
    Domain: atlantis.com
  - Name: Nevergreen
    Domain: nevergreen.nl
  - Name: Valhalla
    Domain: valhalla.asgard
      
# ---------------------------------------------------------------------------
# Used to create external orderer org TLS CA secrets.
# Required if this part of Fabric network is not running an orderer node
# and needs to connect an external orderer.
# Additionally init.sh script creates empty placeholder MSP and TLS folders for convenience.
# It's user's responsibility to copy MSP and TLS certificates to created folders.
# ---------------------------------------------------------------------------
ExternalOrdererOrgs:
  - Name: Pivt
    Domain: pivt.nl
    Specs:
      - Hostname: orderer0
           