# Default values for hlf-kube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# number of times to retry a failed leaf task
retryCount: 4

backup:
  # if not specified defaults to current date
  key: 
  target: 
    # only azureBlobStorage for now, feel free to implement S3
    type: azureBlobStorage
    azureBlobStorage: 
      # storage account name
      accountName: 
      # container name in storage account
      destination: hlf-backup 
      # credentials
      accessKey: 

flow:
  peer:
    backup: 
      # take backup of peers?
      enabled: true
  couchdb:
    backup: 
      # take backup of CouchDB's?
      enabled: true
  orderer:
    replicas: 1
    backup: 
      # take backup of orderers?
      enabled: true
      


